version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
